import Head from "next/head";
import Landing from "@/components/home/Landing";
import Features from "@/components/home/Features";
import Redis from "@/components/home/Redis";
import Footer from "@/components/home/Footer";

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>RediSafe</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>
      <Landing />
      <Features />
      <Redis />
      <Footer />
    </div>
  );
}
